<?php
declare(strict_types=1);
require __DIR__ . '/app.php';
if (!installed()) redirect('install.php');
require_admin();
$section=(string)($_GET['section']??'dashboard');

if ($section==='export') {
    header('Content-Type: text/csv; charset=UTF-8');
    header('Content-Disposition: attachment; filename="bao-cao-tien-do-'.date('Y-m-d').'.csv"');
    $out=fopen('php://output','wb'); fwrite($out,"\xEF\xBB\xBF");
    fputcsv($out,['Họ tên','Email','Đơn vị','Khóa học','Số bài hoàn thành','Tổng số bài','Tỷ lệ (%)','Điểm tốt nhất','Hoạt động cuối']);
    $sql='SELECT u.full_name,u.email,u.unit_name,c.title,COUNT(DISTINCT CASE WHEN p.status="completed" THEN l.id END) done,COUNT(DISTINCT l.id) total,ROUND(COUNT(DISTINCT CASE WHEN p.status="completed" THEN l.id END)*100/NULLIF(COUNT(DISTINCT l.id),0),0) percent,MAX(p.best_score) best_score,MAX(p.updated_at) last_activity FROM users u CROSS JOIN courses c JOIN lessons l ON l.course_id=c.id AND l.status="published" LEFT JOIN progress p ON p.user_id=u.id AND p.lesson_id=l.id WHERE u.role="learner" GROUP BY u.id,c.id ORDER BY u.full_name,c.sort_order';
    foreach(db()->query($sql) as $r) fputcsv($out,array_map('csv_safe',$r)); audit_log('export_progress','report'); fclose($out); exit;
}

if ($_SERVER['REQUEST_METHOD']==='POST') {
    require_csrf(); $action=(string)($_POST['action']??'');
    try {
        if($action==='save_course'){
            $id=(int)($_POST['id']??0);$title=trim((string)$_POST['title']);$slug=trim((string)($_POST['slug']??''))?:slugify($title);
            $data=[$slug,$title,trim((string)($_POST['summary']??'')),json_encode(array_values(array_filter(array_map('trim',preg_split('/\r\n|\r|\n/',(string)($_POST['outcomes']??''))))),JSON_UNESCAPED_UNICODE),(int)($_POST['duration']??0),trim((string)($_POST['level']??'')),trim((string)($_POST['audience']??'all')),trim((string)($_POST['category']??'skills')),trim((string)($_POST['tone']??'blue')),trim((string)($_POST['label']??'')),($_POST['status']??'draft')==='published'?'published':'draft',(int)($_POST['sort_order']??0)];
            if($id){$st=db()->prepare('UPDATE courses SET slug=?,title=?,summary=?,outcomes=?,duration=?,level=?,audience=?,category=?,tone=?,label=?,status=?,sort_order=? WHERE id=?');$st->execute([...$data,$id]);}
            else{$st=db()->prepare('INSERT INTO courses(slug,title,summary,outcomes,duration,level,audience,category,tone,label,status,sort_order) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)');$st->execute($data);$id=(int)db()->lastInsertId();}
            if(array_key_exists('sources',$_POST)){$pdo=db();$pdo->prepare('DELETE FROM course_sources WHERE course_id=?')->execute([$id]);$add=$pdo->prepare('INSERT INTO course_sources(course_id,title,source_url,reviewed_at) VALUES(?,?,?,?)');foreach(preg_split('/\r\n|\r|\n/',(string)$_POST['sources']) as $line){$parts=array_map('trim',explode('|',$line,2));if(count($parts)===2&&filter_var($parts[1],FILTER_VALIDATE_URL))$add->execute([$id,$parts[0],$parts[1],date('Y-m-d')]);}}
            audit_log('save_course','course',$id,['title'=>$title]);
            flash('success','Đã lưu khóa học.');redirect('admin.php?section=course-edit&id='.$id);
        }
        if($action==='delete_course'){
            $id=(int)$_POST['id'];db()->prepare('DELETE FROM courses WHERE id=?')->execute([$id]);flash('success','Đã xóa khóa học và toàn bộ bài liên quan.');redirect('admin.php?section=courses');
        }
        if($action==='save_path'){
            $id=(int)($_POST['id']??0);$title=trim((string)$_POST['title']);$slug=trim((string)($_POST['slug']??''))?:slugify($title);$data=[$slug,$title,trim((string)$_POST['audience']),trim((string)$_POST['level']),trim((string)($_POST['summary']??'')),trim((string)($_POST['legal_basis']??'')),($_POST['status']??'draft')==='published'?'published':'draft',(int)($_POST['sort_order']??0)];$pdo=db();$pdo->beginTransaction();
            if($id){$pdo->prepare('UPDATE learning_paths SET slug=?,title=?,audience=?,level=?,summary=?,legal_basis=?,status=?,sort_order=? WHERE id=?')->execute([...$data,$id]);}else{$pdo->prepare('INSERT INTO learning_paths(slug,title,audience,level,summary,legal_basis,status,sort_order) VALUES(?,?,?,?,?,?,?,?)')->execute($data);$id=(int)$pdo->lastInsertId();}
            $pdo->prepare('DELETE FROM learning_path_courses WHERE path_id=?')->execute([$id]);$add=$pdo->prepare('INSERT INTO learning_path_courses(path_id,course_id,sort_order) VALUES(?,?,?)');foreach(array_values(array_unique(array_map('intval',(array)($_POST['course_ids']??[])))) as $i=>$courseId)if($courseId>0)$add->execute([$id,$courseId,$i+1]);$pdo->commit();audit_log('save_path','learning_path',$id,['title'=>$title]);flash('success','Đã lưu lộ trình.');redirect('admin.php?section=path-edit&id='.$id);
        }
        if($action==='delete_path'){$id=(int)$_POST['id'];db()->prepare('DELETE FROM learning_paths WHERE id=?')->execute([$id]);audit_log('delete_path','learning_path',$id);flash('success','Đã xóa lộ trình.');redirect('admin.php?section=paths');}
        if($action==='save_lesson'){
            $id=(int)($_POST['id']??0);$courseId=(int)$_POST['course_id'];
            $video=trim((string)($_POST['video_url']??''));if($video!==''&&!video_embed_url($video))throw new RuntimeException('Video chỉ chấp nhận liên kết YouTube hợp lệ.');
            $data=[$courseId,trim((string)$_POST['title']),trim((string)($_POST['objective']??'')),trim((string)($_POST['content']??'')),trim((string)($_POST['scenario']??'')),trim((string)($_POST['practice']??'')),$video,(int)($_POST['video_required_percent']??80),trim((string)($_POST['source_note']??'')),date('Y-m-d'),(int)($_POST['duration']??5),(int)($_POST['sort_order']??0),($_POST['status']??'draft')==='published'?'published':'draft'];
            if($id){$st=db()->prepare('UPDATE lessons SET course_id=?,title=?,objective=?,content=?,scenario=?,practice=?,video_url=?,video_required_percent=?,source_note=?,reviewed_at=?,duration=?,sort_order=?,status=? WHERE id=?');$st->execute([...$data,$id]);}
            else{$st=db()->prepare('INSERT INTO lessons(course_id,title,objective,content,scenario,practice,video_url,video_required_percent,source_note,reviewed_at,duration,sort_order,status) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)');$st->execute($data);$id=(int)db()->lastInsertId();}
            audit_log('save_lesson','lesson',$id,['course_id'=>$courseId]);
            flash('success','Đã lưu bài giảng.');redirect('admin.php?section=lesson-edit&id='.$id);
        }
        if($action==='delete_lesson'){$courseId=(int)$_POST['course_id'];db()->prepare('DELETE FROM lessons WHERE id=?')->execute([(int)$_POST['id']]);flash('success','Đã xóa bài giảng.');redirect('admin.php?section=lessons&course_id='.$courseId);}
        if($action==='save_quiz'){
            $id=(int)($_POST['id']??0);$lessonId=(int)$_POST['lesson_id'];$question=trim((string)$_POST['question']);$explanation=trim((string)($_POST['explanation']??''));
            $options=array_values(array_filter(array_map('trim',(array)($_POST['options']??[])),fn($v)=>$v!==''));$correct=(int)($_POST['correct']??0);
            if(count($options)<2)throw new RuntimeException('Quiz cần ít nhất 2 phương án.'); if(!isset($options[$correct]))throw new RuntimeException('Vui lòng chọn đáp án đúng.');
            $pdo=db();$pdo->beginTransaction();
            if($id){$pdo->prepare('UPDATE quizzes SET question=?,explanation=? WHERE id=?')->execute([$question,$explanation,$id]);$pdo->prepare('DELETE FROM quiz_options WHERE quiz_id=?')->execute([$id]);}
            else{$pdo->prepare('INSERT INTO quizzes(lesson_id,question,explanation,sort_order) VALUES(?,?,?,?)')->execute([$lessonId,$question,$explanation,(int)($_POST['sort_order']??0)]);$id=(int)$pdo->lastInsertId();}
            $st=$pdo->prepare('INSERT INTO quiz_options(quiz_id,option_text,is_correct,sort_order) VALUES(?,?,?,?)');foreach($options as $i=>$option)$st->execute([$id,$option,$i===$correct?1:0,$i+1]);$pdo->commit();
            audit_log('save_quiz','quiz',$id,['lesson_id'=>$lessonId]);
            flash('success','Đã lưu câu hỏi quiz.');redirect('admin.php?section=quizzes&lesson_id='.$lessonId);
        }
        if($action==='delete_quiz'){$lessonId=(int)$_POST['lesson_id'];db()->prepare('DELETE FROM quizzes WHERE id=?')->execute([(int)$_POST['id']]);flash('success','Đã xóa câu hỏi.');redirect('admin.php?section=quizzes&lesson_id='.$lessonId);}
        if($action==='save_user'){
            $id=(int)$_POST['id'];$role=($_POST['role']??'learner')==='admin'?'admin':'learner';$status=($_POST['status']??'active')==='locked'?'locked':'active';
            if($id===(int)user()['id']&&($role!=='admin'||$status!=='active'))throw new RuntimeException('Không thể tự thu hồi quyền quản trị hoặc khóa chính mình.');
            if($id){
                db()->prepare('UPDATE users SET full_name=?,unit_name=?,role=?,status=? WHERE id=?')->execute([trim((string)$_POST['full_name']),trim((string)($_POST['unit_name']??'')),$role,$status,$id]);
                if(!empty($_POST['password'])){if(strlen((string)$_POST['password'])<12)throw new RuntimeException('Mật khẩu mới phải có ít nhất 12 ký tự.');db()->prepare('UPDATE users SET password_hash=? WHERE id=?')->execute([password_hash((string)$_POST['password'],PASSWORD_DEFAULT),$id]);}
            }else{
                $email=mb_strtolower(trim((string)($_POST['email']??'')));$password=(string)($_POST['password']??'');
                if(!filter_var($email,FILTER_VALIDATE_EMAIL))throw new RuntimeException('Email không hợp lệ.');if(strlen($password)<12)throw new RuntimeException('Mật khẩu phải có ít nhất 12 ký tự.');
                db()->prepare('INSERT INTO users(email,password_hash,full_name,unit_name,role,status) VALUES(?,?,?,?,?,?)')->execute([$email,password_hash($password,PASSWORD_DEFAULT),trim((string)$_POST['full_name']),trim((string)($_POST['unit_name']??'')),$role,$status]);$id=(int)db()->lastInsertId();
            }
            audit_log('save_user','user',$id,['role'=>$role,'status'=>$status]);flash('success','Đã cập nhật tài khoản.');redirect('admin.php?section=users');
        }
        if($action==='delete_user'){$id=(int)$_POST['id'];if($id===(int)user()['id'])throw new RuntimeException('Không thể xóa tài khoản đang đăng nhập.');audit_log('delete_user','user',$id);db()->prepare('DELETE FROM users WHERE id=?')->execute([$id]);flash('success','Đã xóa tài khoản và dữ liệu tiến độ liên quan.');redirect('admin.php?section=users');}
        if($action==='save_settings'){
            $st=db()->prepare('INSERT INTO settings(setting_key,setting_value) VALUES(?,?) ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value)');
            foreach(['site_title','site_notice','allow_registration','allowed_email_domain','quiz_pass_score','privacy_retention_months'] as $key)$st->execute([$key,(string)($_POST[$key]??'')]);audit_log('save_settings','settings');flash('success','Đã lưu cấu hình.');redirect('admin.php?section=settings');
        }
    }catch(Throwable $e){if(isset($pdo)&&$pdo->inTransaction())$pdo->rollBack();audit_log('admin_error','system',null,['type'=>get_class($e)]);flash('danger',$e instanceof PDOException?'Không thể lưu dữ liệu. Vui lòng kiểm tra lại hoặc xem nhật ký máy chủ.':$e->getMessage());redirect('admin.php?section='.$section.(!empty($_GET['id'])?'&id='.(int)$_GET['id']:''));}
}

function admin_start(string $title,string $active):void{
    page_header($title,true);$items=['dashboard'=>['Tổng quan','chart'],'courses'=>['Khóa học','book'],'paths'=>['Lộ trình','arrow'],'users'=>['Người dùng','user'],'reports'=>['Báo cáo','chart'],'audit'=>['Nhật ký','lock'],'settings'=>['Cấu hình','edit']];
    echo '<div class="admin-layout"><aside class="admin-side"><h2>Quản trị hệ thống</h2><nav>';foreach($items as $k=>$item)echo '<a class="'.($active===$k?'active':'').'" href="'.url('admin.php?section='.$k).'">'.icon($item[1]).e($item[0]).'</a>';echo '</nav><a class="admin-back" href="'.url('index.php').'">← Xem trang học</a></aside><main class="admin-main"><div class="admin-head"><div><p class="eyebrow">Bảng điều khiển</p><h1>'.e($title).'</h1></div></div>';
}
function admin_end():void{echo '</main></div>';page_footer();}
function confirm_button(string $action,int $id,string $label,array $extra=[]):string{$fields=csrf_field().'<input type="hidden" name="action" value="'.e($action).'"><input type="hidden" name="id" value="'.$id.'">';foreach($extra as $k=>$v)$fields.='<input type="hidden" name="'.e($k).'" value="'.e((string)$v).'">';return '<form method="post" class="inline" data-confirm="Hành động này không thể hoàn tác. Tiếp tục?">'.$fields.'<button class="btn-link danger" type="submit">'.e($label).'</button></form>';}

if($section==='dashboard'){
    admin_start('Tổng quan','dashboard');
    $stats=['Người học'=>(int)db()->query('SELECT COUNT(*) FROM users WHERE role="learner"')->fetchColumn(),'Khóa học'=>(int)db()->query('SELECT COUNT(*) FROM courses')->fetchColumn(),'Bài giảng'=>(int)db()->query('SELECT COUNT(*) FROM lessons')->fetchColumn(),'Lượt hoàn thành'=>(int)db()->query('SELECT COUNT(*) FROM progress WHERE status="completed"')->fetchColumn()];
    echo '<div class="stat-grid">';foreach($stats as $label=>$value)echo '<article><span>'.e($label).'</span><strong>'.number_format($value).'</strong></article>';echo '</div><div class="admin-grid"><section class="panel"><div class="panel-head"><h2>Tiến độ theo khóa học</h2><a href="'.url('admin.php?section=reports').'">Xem báo cáo</a></div>';
    $rows=db()->query('SELECT c.title,COUNT(DISTINCT l.id) lessons,COUNT(DISTINCT p.user_id) learners,COUNT(CASE WHEN p.status="completed" THEN 1 END) completions FROM courses c LEFT JOIN lessons l ON l.course_id=c.id LEFT JOIN progress p ON p.lesson_id=l.id GROUP BY c.id ORDER BY completions DESC LIMIT 8')->fetchAll();
    foreach($rows as $r){$max=max(1,(int)$r['lessons']*max(1,(int)$r['learners']));$pct=min(100,(int)round((int)$r['completions']*100/$max));echo '<div class="metric-row"><div><strong>'.e($r['title']).'</strong><span>'.$r['learners'].' người học · '.$r['completions'].' lượt hoàn thành bài</span></div><div class="bar"><span style="width:'.$pct.'%"></span></div></div>';}
    echo '</section><section class="panel"><div class="panel-head"><h2>Hoạt động gần đây</h2></div>';
    $recent=db()->query('SELECT u.full_name,l.title,p.status,p.best_score,p.updated_at FROM progress p JOIN users u ON u.id=p.user_id JOIN lessons l ON l.id=p.lesson_id ORDER BY p.updated_at DESC LIMIT 10')->fetchAll();if(!$recent)echo '<div class="empty">Chưa có hoạt động học tập.</div>';foreach($recent as $r)echo '<div class="activity"><span>'.mb_substr($r['full_name'],0,1).'</span><div><strong>'.e($r['full_name']).'</strong><p>'.($r['status']==='completed'?'hoàn thành':'đã mở').' “'.e($r['title']).'” · '.e((string)$r['best_score']).' điểm</p></div><time>'.e(date('d/m H:i',strtotime($r['updated_at']))).'</time></div>';
    echo '</section></div>';admin_end();exit;
}

if($section==='courses'){
    admin_start('Quản lý khóa học','courses');echo '<div class="actions"><a class="btn" href="'.url('admin.php?section=course-edit').'">+ Thêm khóa học</a></div><section class="panel table-wrap"><table><thead><tr><th>Khóa học</th><th>Trạng thái</th><th>Bài</th><th>Thứ tự</th><th></th></tr></thead><tbody>';
    $rows=db()->query('SELECT c.*,COUNT(l.id) lesson_count FROM courses c LEFT JOIN lessons l ON l.course_id=c.id GROUP BY c.id ORDER BY c.sort_order,c.id')->fetchAll();foreach($rows as $r)echo '<tr><td><strong>'.e($r['title']).'</strong><small>'.e($r['slug']).'</small></td><td><span class="status '.$r['status'].'">'.($r['status']==='published'?'Đang hiện':'Bản nháp').'</span></td><td>'.$r['lesson_count'].'</td><td>'.$r['sort_order'].'</td><td class="row-actions"><a href="'.url('admin.php?section=lessons&course_id='.$r['id']).'">Bài giảng</a><a href="'.url('admin.php?section=course-edit&id='.$r['id']).'">Sửa</a>'.confirm_button('delete_course',(int)$r['id'],'Xóa').'</td></tr>';echo '</tbody></table></section>';admin_end();exit;
}

if($section==='course-edit'){
    $id=(int)($_GET['id']??0);$c=['id'=>0,'slug'=>'','title'=>'','summary'=>'','outcomes'=>'[]','duration'=>20,'level'=>'Cơ bản','audience'=>'all','category'=>'skills','tone'=>'blue','label'=>'','status'=>'draft','sort_order'=>0];if($id){$st=db()->prepare('SELECT * FROM courses WHERE id=?');$st->execute([$id]);$c=$st->fetch()?:$c;}
    admin_start($id?'Sửa khóa học':'Thêm khóa học','courses');$outcomes=implode("\n",(array)json_decode($c['outcomes']?:'[]',true));$sources='';if($id){$ss=db()->prepare('SELECT title,source_url FROM course_sources WHERE course_id=? ORDER BY id');$ss->execute([$id]);foreach($ss as $s)$sources.=$s['title'].' | '.$s['source_url']."\n";}
    echo '<form method="post" class="panel form-grid">'.csrf_field().'<input type="hidden" name="action" value="save_course"><input type="hidden" name="id" value="'.$id.'"><label class="span-2">Tên khóa học<input name="title" required value="'.e($c['title']).'"></label><label>Đường dẫn rút gọn<input name="slug" value="'.e($c['slug']).'" placeholder="Tự tạo nếu để trống"></label><label>Trạng thái<select name="status"><option value="published" '.($c['status']==='published'?'selected':'').'>Đang hiển thị</option><option value="draft" '.($c['status']==='draft'?'selected':'').'>Bản nháp</option></select></label><label class="span-2">Mô tả<textarea name="summary" rows="3">'.e($c['summary']).'</textarea></label><label class="span-2">Kết quả cần đạt <small>Mỗi dòng một ý</small><textarea name="outcomes" rows="5">'.e($outcomes).'</textarea></label><label class="span-2">Nguồn chính thức <small>Mỗi dòng: Tên nguồn | https://...</small><textarea name="sources" rows="5">'.e(trim($sources)).'</textarea></label><label>Thời lượng (phút)<input type="number" name="duration" min="0" value="'.(int)$c['duration'].'"></label><label>Cấp độ<input name="level" value="'.e($c['level']).'"></label><label>Đối tượng<select name="audience"><option value="all" '.($c['audience']==='all'?'selected':'').'>Tất cả</option><option value="cbvc" '.($c['audience']==='cbvc'?'selected':'').'>CBVC</option><option value="student" '.($c['audience']==='student'?'selected':'').'>Sinh viên</option><option value="cbvc,student" '.($c['audience']==='cbvc,student'?'selected':'').'>CBVC và sinh viên</option></select></label><label>Chủ đề<select name="category">';foreach(['skills'=>'Kỹ năng số','safety'=>'An toàn số','ai'=>'Trí tuệ nhân tạo','services'=>'Dịch vụ số','data'=>'Dữ liệu','admin'=>'Hành chính số'] as $v=>$label)echo '<option value="'.$v.'" '.($c['category']===$v?'selected':'').'>'.$label.'</option>';echo '</select></label><label>Màu sắc<select name="tone">';foreach(['blue'=>'Xanh dương','teal'=>'Xanh ngọc','purple'=>'Tím','red'=>'Đỏ HPU2','gold'=>'Vàng'] as $v=>$label)echo '<option value="'.$v.'" '.($c['tone']===$v?'selected':'').'>'.$label.'</option>';echo '</select></label><label>Nhãn hiển thị<input name="label" value="'.e($c['label']).'"></label><label>Thứ tự<input type="number" name="sort_order" value="'.(int)$c['sort_order'].'"></label><div class="form-actions span-2"><button class="btn">Lưu khóa học</button><a class="btn btn-ghost" href="'.url('admin.php?section=courses').'">Quay lại</a>'.($id?'<a class="btn btn-ghost" href="'.url('admin.php?section=lessons&course_id='.$id).'">Quản lý bài giảng</a>':'').'</div></form>';admin_end();exit;
}

if($section==='lessons'){
    $courseId=(int)($_GET['course_id']??0);$st=db()->prepare('SELECT * FROM courses WHERE id=?');$st->execute([$courseId]);$course=$st->fetch();if(!$course){http_response_code(404);exit('Không tìm thấy khóa học.');}
    admin_start('Bài giảng · '.$course['title'],'courses');echo '<div class="actions"><a class="btn" href="'.url('admin.php?section=lesson-edit&course_id='.$courseId).'">+ Thêm bài giảng</a><a class="btn btn-ghost" href="'.url('admin.php?section=course-edit&id='.$courseId).'">Sửa khóa học</a></div><section class="panel table-wrap"><table><thead><tr><th>Thứ tự</th><th>Bài giảng</th><th>Quiz</th><th>Trạng thái</th><th></th></tr></thead><tbody>';
    $st=db()->prepare('SELECT l.*,COUNT(q.id) quiz_count FROM lessons l LEFT JOIN quizzes q ON q.lesson_id=l.id WHERE l.course_id=? GROUP BY l.id ORDER BY l.sort_order,l.id');$st->execute([$courseId]);foreach($st as $r)echo '<tr><td>'.$r['sort_order'].'</td><td><strong>'.e($r['title']).'</strong><small>'.$r['duration'].' phút</small></td><td>'.$r['quiz_count'].' câu</td><td><span class="status '.$r['status'].'">'.($r['status']==='published'?'Đang hiện':'Bản nháp').'</span></td><td class="row-actions"><a href="'.url('admin.php?section=quizzes&lesson_id='.$r['id']).'">Quiz</a><a href="'.url('admin.php?section=lesson-edit&id='.$r['id']).'">Sửa</a>'.confirm_button('delete_lesson',(int)$r['id'],'Xóa',['course_id'=>$courseId]).'</td></tr>';echo '</tbody></table></section>';admin_end();exit;
}

if($section==='lesson-edit'){
    $id=(int)($_GET['id']??0);$courseId=(int)($_GET['course_id']??0);$l=['id'=>0,'course_id'=>$courseId,'title'=>'','objective'=>'','content'=>'','scenario'=>'','practice'=>'','video_url'=>'','video_required_percent'=>80,'source_note'=>'','duration'=>5,'sort_order'=>0,'status'=>'draft'];if($id){$st=db()->prepare('SELECT * FROM lessons WHERE id=?');$st->execute([$id]);$l=$st->fetch()?:$l;$courseId=(int)$l['course_id'];}
    admin_start($id?'Sửa bài giảng':'Thêm bài giảng','courses');echo '<form method="post" class="panel form-grid">'.csrf_field().'<input type="hidden" name="action" value="save_lesson"><input type="hidden" name="id" value="'.$id.'"><input type="hidden" name="course_id" value="'.$courseId.'"><label class="span-2">Tên bài giảng<input name="title" required value="'.e($l['title']).'"></label><label class="span-2">Mục tiêu<textarea name="objective" rows="2">'.e($l['objective']).'</textarea></label><label class="span-2">Nội dung chính <small>Mỗi dòng là một ý hiển thị</small><textarea name="content" rows="10">'.e($l['content']).'</textarea></label><label class="span-2">Tình huống thực tế<textarea name="scenario" rows="4">'.e($l['scenario']).'</textarea></label><label class="span-2">Bài thực hành<textarea name="practice" rows="4">'.e($l['practice']).'</textarea></label><label class="span-2">Video YouTube <small>Dán URL youtube.com/watch hoặc youtu.be; hệ thống dùng chế độ tăng cường riêng tư</small><input type="url" name="video_url" value="'.e($l['video_url']).'" placeholder="https://youtu.be/..."></label><label>Phần trăm video bắt buộc<input type="number" name="video_required_percent" min="0" max="100" value="'.(int)$l['video_required_percent'].'"></label><label>Nguồn/ghi chú học thuật<input name="source_note" value="'.e($l['source_note']).'"></label><label>Thời lượng (phút)<input type="number" name="duration" min="1" value="'.(int)$l['duration'].'"></label><label>Thứ tự<input type="number" name="sort_order" value="'.(int)$l['sort_order'].'"></label><label>Trạng thái<select name="status"><option value="published" '.($l['status']==='published'?'selected':'').'>Đang hiển thị</option><option value="draft" '.($l['status']==='draft'?'selected':'').'>Bản nháp</option></select></label><div class="form-actions span-2"><button class="btn">Lưu bài giảng</button><a class="btn btn-ghost" href="'.url('admin.php?section=lessons&course_id='.$courseId).'">Quay lại</a>'.($id?'<a class="btn btn-ghost" href="'.url('admin.php?section=quizzes&lesson_id='.$id).'">Quản lý quiz</a>':'').'</div></form>';admin_end();exit;
}

if($section==='quizzes'){
    $lessonId=(int)($_GET['lesson_id']??0);$st=db()->prepare('SELECT l.*,c.title course_title FROM lessons l JOIN courses c ON c.id=l.course_id WHERE l.id=?');$st->execute([$lessonId]);$lesson=$st->fetch();if(!$lesson){http_response_code(404);exit('Không tìm thấy bài học.');}
    admin_start('Quiz · '.$lesson['title'],'courses');echo '<div class="actions"><a class="btn" href="'.url('admin.php?section=quiz-edit&lesson_id='.$lessonId).'">+ Thêm câu hỏi</a><a class="btn btn-ghost" href="'.url('admin.php?section=lesson-edit&id='.$lessonId).'">Sửa bài giảng</a></div><section class="panel">';$st=db()->prepare('SELECT * FROM quizzes WHERE lesson_id=? ORDER BY sort_order,id');$st->execute([$lessonId]);$rows=$st->fetchAll();if(!$rows)echo '<div class="empty">Chưa có câu hỏi. Người học chưa thể hoàn thành bài này.</div>';foreach($rows as $i=>$q){echo '<article class="quiz-admin"><div><span>Câu '.($i+1).'</span><h3>'.e($q['question']).'</h3><ol>';$os=db()->prepare('SELECT * FROM quiz_options WHERE quiz_id=? ORDER BY sort_order,id');$os->execute([$q['id']]);foreach($os as $o)echo '<li class="'.($o['is_correct']?'correct':'').'">'.e($o['option_text']).($o['is_correct']?' ✓':'').'</li>';echo '</ol></div><div class="row-actions"><a href="'.url('admin.php?section=quiz-edit&id='.$q['id']).'">Sửa</a>'.confirm_button('delete_quiz',(int)$q['id'],'Xóa',['lesson_id'=>$lessonId]).'</div></article>';}echo '</section>';admin_end();exit;
}

if($section==='quiz-edit'){
    $id=(int)($_GET['id']??0);$lessonId=(int)($_GET['lesson_id']??0);$q=['id'=>0,'lesson_id'=>$lessonId,'question'=>'','explanation'=>'','sort_order'=>0];$options=['','',''];$correct=0;if($id){$st=db()->prepare('SELECT * FROM quizzes WHERE id=?');$st->execute([$id]);$q=$st->fetch()?:$q;$lessonId=(int)$q['lesson_id'];$os=db()->prepare('SELECT * FROM quiz_options WHERE quiz_id=? ORDER BY sort_order,id');$os->execute([$id]);$rows=$os->fetchAll();$options=array_column($rows,'option_text');foreach($rows as $i=>$o)if($o['is_correct'])$correct=$i;}
    while(count($options)<4)$options[]='';admin_start($id?'Sửa câu hỏi':'Thêm câu hỏi','courses');echo '<form method="post" class="panel form-grid">'.csrf_field().'<input type="hidden" name="action" value="save_quiz"><input type="hidden" name="id" value="'.$id.'"><input type="hidden" name="lesson_id" value="'.$lessonId.'"><label class="span-2">Câu hỏi<textarea name="question" rows="3" required>'.e($q['question']).'</textarea></label><div class="span-2"><strong>Các phương án</strong><p class="muted">Chọn nút tròn ở phương án đúng. Có thể để trống phương án không dùng.</p><div class="option-editor">';foreach($options as $i=>$o)echo '<label><input type="radio" name="correct" value="'.$i.'" '.($i===$correct?'checked':'').'><input name="options[]" value="'.e($o).'" placeholder="Phương án '.($i+1).'" '.($i<2?'required':'').'></label>';echo '</div></div><label class="span-2">Giải thích sau khi trả lời<textarea name="explanation" rows="3">'.e($q['explanation']).'</textarea></label><label>Thứ tự<input type="number" name="sort_order" value="'.(int)$q['sort_order'].'"></label><div class="form-actions span-2"><button class="btn">Lưu câu hỏi</button><a class="btn btn-ghost" href="'.url('admin.php?section=quizzes&lesson_id='.$lessonId).'">Quay lại</a></div></form>';admin_end();exit;
}

if($section==='paths'){
    admin_start('Lộ trình học','paths');echo '<div class="actions"><a class="btn" href="'.url('admin.php?section=path-edit').'">+ Thêm lộ trình</a></div><section class="panel table-wrap"><table><thead><tr><th>Lộ trình</th><th>Nhóm học</th><th>Khóa học</th><th>Trạng thái</th><th></th></tr></thead><tbody>';$rows=db()->query('SELECT p.*,COUNT(pc.course_id) course_count FROM learning_paths p LEFT JOIN learning_path_courses pc ON pc.path_id=p.id GROUP BY p.id ORDER BY p.sort_order,p.id')->fetchAll();foreach($rows as $r)echo '<tr><td><strong>'.e($r['title']).'</strong><small>'.e($r['level']).'</small></td><td>'.e($r['audience']).'</td><td>'.(int)$r['course_count'].'</td><td><span class="status '.e($r['status']).'">'.($r['status']==='published'?'Đang hiển thị':'Bản nháp').'</span></td><td class="row-actions"><a href="'.url('admin.php?section=path-edit&id='.$r['id']).'">Sửa</a>'.confirm_button('delete_path',(int)$r['id'],'Xóa').'</td></tr>';echo '</tbody></table></section>';admin_end();exit;
}

if($section==='path-edit'){
    $id=(int)($_GET['id']??0);$p=['slug'=>'','title'=>'','audience'=>'','level'=>'Cơ bản','summary'=>'','legal_basis'=>'','status'=>'published','sort_order'=>0];$selected=[];if($id){$st=db()->prepare('SELECT * FROM learning_paths WHERE id=?');$st->execute([$id]);$p=$st->fetch();if(!$p){http_response_code(404);exit('Không tìm thấy lộ trình.');}$st=db()->prepare('SELECT course_id FROM learning_path_courses WHERE path_id=? ORDER BY sort_order');$st->execute([$id]);$selected=array_map('intval',$st->fetchAll(PDO::FETCH_COLUMN));}$courses=db()->query('SELECT id,title,status FROM courses ORDER BY sort_order,id')->fetchAll();admin_start($id?'Sửa lộ trình':'Thêm lộ trình','paths');echo '<form method="post" class="panel form-grid">'.csrf_field().'<input type="hidden" name="action" value="save_path"><input type="hidden" name="id" value="'.$id.'"><label>Tên lộ trình<input name="title" required value="'.e($p['title']).'"></label><label>Đường dẫn<input name="slug" value="'.e($p['slug']).'" placeholder="tự tạo nếu để trống"></label><label>Nhóm người học<input name="audience" required value="'.e($p['audience']).'"></label><label>Cấp độ<input name="level" required value="'.e($p['level']).'"></label><label class="span-2">Mô tả<textarea name="summary" rows="3">'.e($p['summary']).'</textarea></label><label class="span-2">Căn cứ / khung tham chiếu<textarea name="legal_basis" rows="3">'.e($p['legal_basis']).'</textarea></label><div class="span-2"><strong>Khóa học trong lộ trình</strong><p class="muted">Thứ tự hiển thị theo danh sách dưới đây.</p><div class="check-grid">';foreach($courses as $c)echo '<label class="check-card"><input type="checkbox" name="course_ids[]" value="'.$c['id'].'" '.(in_array((int)$c['id'],$selected,true)?'checked':'').'><span>'.e($c['title']).($c['status']==='draft'?' (bản nháp)':'').'</span></label>';echo '</div></div><label>Thứ tự<input type="number" name="sort_order" value="'.(int)$p['sort_order'].'"></label><label>Trạng thái<select name="status"><option value="published" '.($p['status']==='published'?'selected':'').'>Đang hiển thị</option><option value="draft" '.($p['status']==='draft'?'selected':'').'>Bản nháp</option></select></label><div class="form-actions span-2"><button class="btn">Lưu lộ trình</button><a class="btn btn-ghost" href="'.url('admin.php?section=paths').'">Quay lại</a></div></form>';admin_end();exit;
}

if($section==='users'){
    $pageNo=max(1,(int)($_GET['p']??1));$perPage=50;$total=(int)db()->query('SELECT COUNT(*) FROM users')->fetchColumn();$offset=($pageNo-1)*$perPage;$st=db()->prepare('SELECT * FROM users ORDER BY role="admin" DESC,created_at DESC LIMIT ? OFFSET ?');$st->bindValue(1,$perPage,PDO::PARAM_INT);$st->bindValue(2,$offset,PDO::PARAM_INT);$st->execute();$rows=$st->fetchAll();admin_start('Người dùng','users');echo '<div class="actions"><a class="btn" href="'.url('admin.php?section=user-edit').'">+ Thêm tài khoản</a><span class="muted">'.number_format($total,0,',','.').' tài khoản</span></div><section class="panel table-wrap"><table><thead><tr><th>Người dùng</th><th>Đơn vị</th><th>Vai trò</th><th>Trạng thái</th><th>Đăng nhập cuối</th><th></th></tr></thead><tbody>';foreach($rows as $r)echo '<tr><td><strong>'.e($r['full_name']).'</strong><small>'.e($r['email']).'</small></td><td>'.e($r['unit_name']).'</td><td>'.($r['role']==='admin'?'Quản trị':'Học viên').'</td><td><span class="status '.$r['status'].'">'.($r['status']==='active'?'Hoạt động':'Đã khóa').'</span></td><td>'.($r['last_login_at']?date('d/m/Y H:i',strtotime($r['last_login_at'])):'—').'</td><td class="row-actions"><a href="'.url('admin.php?section=user-edit&id='.$r['id']).'">Sửa</a>'.($r['id']!=user()['id']?confirm_button('delete_user',(int)$r['id'],'Xóa'):'').'</td></tr>';echo '</tbody></table></section>';if($total>$perPage){echo '<nav class="pagination">';for($i=1;$i<=ceil($total/$perPage);$i++)echo '<a class="'.($i===$pageNo?'active':'').'" href="'.url('admin.php?section=users&p='.$i).'">'.$i.'</a>';echo '</nav>';}admin_end();exit;
}

if($section==='user-edit'){
    $id=(int)($_GET['id']??0);$u=['email'=>'','full_name'=>'','unit_name'=>'','role'=>'learner','status'=>'active'];if($id){$st=db()->prepare('SELECT * FROM users WHERE id=?');$st->execute([$id]);$u=$st->fetch();if(!$u){http_response_code(404);exit('Không tìm thấy người dùng.');}}admin_start($id?'Sửa tài khoản':'Thêm tài khoản','users');echo '<form method="post" class="panel form-grid">'.csrf_field().'<input type="hidden" name="action" value="save_user"><input type="hidden" name="id" value="'.$id.'"><label>Họ tên<input name="full_name" required value="'.e($u['full_name']).'"></label><label>Email<input type="email" name="email" '.($id?'disabled':'required').' value="'.e($u['email']).'"></label><label>Đơn vị<input name="unit_name" value="'.e($u['unit_name']).'"></label><label>Vai trò<select name="role"><option value="learner" '.($u['role']==='learner'?'selected':'').'>Học viên</option><option value="admin" '.($u['role']==='admin'?'selected':'').'>Quản trị</option></select></label><label>Trạng thái<select name="status"><option value="active" '.($u['status']==='active'?'selected':'').'>Hoạt động</option><option value="locked" '.($u['status']==='locked'?'selected':'').'>Khóa</option></select></label><label>'.($id?'Mật khẩu mới <small>Để trống nếu không đổi</small>':'Mật khẩu ban đầu').'<input type="password" name="password" minlength="8" '.($id?'':'required').'></label><div class="form-actions span-2"><button class="btn">Lưu tài khoản</button><a class="btn btn-ghost" href="'.url('admin.php?section=users').'">Quay lại</a></div></form>';admin_end();exit;
}

if($section==='reports'){
    admin_start('Báo cáo học tập','reports');echo '<div class="actions"><a class="btn" href="'.url('admin.php?section=export').'">Xuất Excel/CSV</a></div><section class="panel table-wrap"><table><thead><tr><th>Học viên</th><th>Đơn vị</th><th>Đã học</th><th>Hoàn thành</th><th>Điểm tốt nhất</th><th>Hoạt động cuối</th></tr></thead><tbody>';
    $sql='SELECT u.id,u.full_name,u.email,u.unit_name,COUNT(DISTINCT p.lesson_id) started,COUNT(DISTINCT CASE WHEN p.status="completed" THEN p.lesson_id END) done,MAX(p.best_score) best_score,MAX(p.updated_at) last_activity FROM users u LEFT JOIN progress p ON p.user_id=u.id WHERE u.role="learner" GROUP BY u.id ORDER BY last_activity DESC,u.full_name';foreach(db()->query($sql) as $r)echo '<tr><td><strong>'.e($r['full_name']).'</strong><small>'.e($r['email']).'</small></td><td>'.e($r['unit_name']).'</td><td>'.$r['started'].' bài</td><td>'.$r['done'].' bài</td><td>'.($r['best_score']!==null?e((string)$r['best_score']).' điểm':'—').'</td><td>'.($r['last_activity']?date('d/m/Y H:i',strtotime($r['last_activity'])):'Chưa học').'</td></tr>';echo '</tbody></table></section>';admin_end();exit;
}

if($section==='audit'){
    admin_start('Nhật ký quản trị','audit');echo '<section class="panel table-wrap"><table><thead><tr><th>Thời gian</th><th>Người thực hiện</th><th>Hành động</th><th>Đối tượng</th><th>Địa chỉ IP</th></tr></thead><tbody>';
    $rows=db()->query('SELECT a.*,u.full_name FROM audit_logs a LEFT JOIN users u ON u.id=a.user_id ORDER BY a.created_at DESC LIMIT 300')->fetchAll();foreach($rows as $r)echo '<tr><td>'.e(date('d/m/Y H:i:s',strtotime($r['created_at']))).'</td><td>'.e($r['full_name']?:'Hệ thống').'</td><td><strong>'.e($r['action']).'</strong></td><td>'.e($r['object_type']).($r['object_id']?' #'.(int)$r['object_id']:'').'</td><td>'.e($r['ip_address']).'</td></tr>';if(!$rows)echo '<tr><td colspan="5" class="empty">Chưa có sự kiện.</td></tr>';echo '</tbody></table></section>';admin_end();exit;
}

if($section==='settings'){
    admin_start('Cấu hình hệ thống','settings');echo '<form method="post" class="panel form-grid">'.csrf_field().'<input type="hidden" name="action" value="save_settings"><label class="span-2">Tên website<input name="site_title" value="'.e(setting('site_title','Bình dân học vụ số HPU2')).'"></label><label class="span-2">Thông báo trên trang chủ<textarea name="site_notice" rows="3">'.e(setting('site_notice','')).'</textarea></label><label>Cho phép gửi yêu cầu đăng ký<select name="allow_registration"><option value="1" '.(setting('allow_registration','0')==='1'?'selected':'').'>Có, nhưng chờ quản trị duyệt</option><option value="0" '.(setting('allow_registration','0')==='0'?'selected':'').'>Không (khuyến nghị)</option></select></label><label>Miền email được đăng ký<input name="allowed_email_domain" value="'.e(setting('allowed_email_domain','hpu2.edu.vn')).'" placeholder="hpu2.edu.vn"></label><label>Điểm đạt quiz (%)<input type="number" min="1" max="100" name="quiz_pass_score" value="'.e(setting('quiz_pass_score','70')).'"></label><label>Thời hạn lưu dữ liệu (tháng)<input type="number" min="1" max="120" name="privacy_retention_months" value="'.e(setting('privacy_retention_months','24')).'"></label><div class="span-2 alert alert-warning"><strong>Lưu ý:</strong> miền email chỉ là điều kiện định dạng, không xác minh danh tính. Khi triển khai thật nên tắt tự đăng ký và tạo tài khoản qua quản trị/SSO HPU2.</div><div class="form-actions span-2"><button class="btn">Lưu cấu hình</button></div></form>';admin_end();exit;
}

http_response_code(404);exit('Trang quản trị không tồn tại.');
